language: minimal
dist: bionic

git:
  quiet: true

services:
  - docker

before_script:
  - docker pull haskell:latest
  - docker run -dit --name haskell-build -v $TRAVIS_BUILD_DIR:/shared -w=/shared haskell bash

script:
- docker exec haskell-build stack --allow-different-user setup
- docker exec haskell-build stack --allow-different-user build --test

after_script:
- docker stop haskell-build