language: minimal
dist: bionic

git:
  quiet: true

services:
  - docker

before_script:
  - docker pull haskell:latest
  - docker run -dit --name haskell-build -v $TRAVIS_BUILD_DIR:/shared -w=/shared haskell bash

script:
  - docker exec haskell-build sh -c "apt-get update && apt-get install locales -y && echo 'en_US.UTF-8 UTF-8' > /etc/locales.gen && echo 'LANG=\"en_US.UTF-8\"' > /etc/default/locale && locale-gen && export LC_ALL=en_US.UTF-8&& stack --allow-different-user setup && LC_ALL=en_US.UTF-8 stack --allow-different-user build --test"

after_script:
- docker stop haskell-build
