language: minimal
dist: bionic

git:
  quiet: true

addons:
  apt:
    sources:
      - sourceline: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /'
        key_url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key'
    update: true
    packages:
      - buildah
      - yum

before_script:
  - echo $quayiopassword | buildah login -u $quayiouser --password-stdin quay.io
  - echo $githubtoken | buildah login -u $githublogin --password-stdin ghcr.io

script:
  - sudo ./build.sh

after_success:
  - sudo buildah push schy:latest docker://quay.io/$quayiouser/schy:latest
  - sudo buildah push schy:latest docker://ghcr.io/$githublogin/schy:latest

after_script:
  - docker logout quay.io
  - docker logout ghcr.io
