language: minimal
dist: bionic

git:
  quiet: true

services:
  - docker

before_script:
  - docker pull haskell:latest
  - docker run -dit --name haskell-build -v $TRAVIS_BUILD_DIR:/shared -w=/shared haskell bash

script:
- docker exec haskell-build apt-get update
- docker exec haskell-build apt-get install locales -y
- docker exec haskell-build sh -c "echo 'en_US.UTF-8 UTF-8' > /etc/locales.gen"
- docker exec haskell-build sh -c "echo 'LANG=\"en_US.UTF-8\"' > /etc/default/locale"
- docker exec haskell-build locale-gen
- docker exec haskell-build sh -c 'export LC_ALL=en_US.UTF-8'
- docker exec haskell-build stack --allow-different-user setup
- docker exec haskell-build sh -c 'LC_ALL=en_US.UTF-8 stack --allow-different-user build --test'

after_script:
- docker stop haskell-build